# Generated by Django 2.1.4 on 2018-12-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AssetObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('path_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=40)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imperium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('game_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.GameVersion')),
            ],
        ),
        migrations.CreateModel(
            name='TranslateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('text', models.TextField(null=True)),
                ('language', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='assetbundle',
            name='imperium',
            field=models.ManyToManyField(to='api.Imperium'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssetBundle'),
        ),
    ]
