# Generated by Django 2.1.4 on 2018-12-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181217_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='imperium',
            name='md5',
            field=models.CharField(default='0000000000', max_length=32),
            preserve_default=False,
        ),
    ]
