# Generated by Django 2.1.5 on 2019-01-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181225_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='imperium',
            name='celery_task_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='imperium',
            name='type_id',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'gamedata'), (2, 'android'), (3, 'androidExp'), (4, 'localization'), (5, 'charAssets'), (6, 'settings')], default=0),
        ),
    ]
