# Generated by Django 2.1.5 on 2019-01-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190127_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='imperium',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
