# Generated by Django 2.1.5 on 2019-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imperium_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='assetbundle',
            old_name='imperium',
            new_name='imperiums',
        ),
        migrations.AddField(
            model_name='assetbundle',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='asset_bundles',
            field=models.ManyToManyField(to='api.AssetBundle'),
        ),
    ]
