# Generated by Django 2.1.5 on 2019-02-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190129_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbundle',
            name='md5',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
