# Generated by Django 2.1.7 on 2019-02-22 15:13
# https://stackoverflow.com/questions/25024795/django-1-7-where-to-put-the-code-to-add-groups-programmatically
from django.contrib.auth.models import Group, Permission
from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def generate_permissions(models_name, permissions):
    return ['%s_%s' % (p, n) for n in models_name for p in permissions]

def add_group_permissions(apps, schema_editor):
    # read_only
    group, created = Group.objects.get_or_create(name='read_only')
    if created:
        # rest framework doesn't check view permission by default
        logger.info('Group read_only created')

    # standard
    group, created = Group.objects.get_or_create(name='standard_user')
    if created:
        group.permissions.set(
            Permission.objects.filter(content_type__app_label='api',
                                      codename__in=generate_permissions(['imperium', 'gameversion', 'convertrule'],
                                                                        ['view', 'create', 'add', 'change', 'delete'])))
        logger.info('Group standard_user created')

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0011_auto_20190220_2215'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
