# Generated by Django 2.1.7 on 2019-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_viewerjs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnityObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('data_crc32', models.BigIntegerField(null=True)),
                ('db_crc32', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnityObjectRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.BigIntegerField()),
                ('asset_index', models.IntegerField(null=True)),
                ('assetbundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AssetBundle')),
                ('unityobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UnityObject')),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_bundle',
        ),
        migrations.RemoveField(
            model_name='assetobject',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='AssetObject',
        ),
        migrations.AddField(
            model_name='unityobject',
            name='asset_bundles',
            field=models.ManyToManyField(through='api.UnityObjectRelationship', to='api.AssetBundle'),
        ),
    ]
