# Generated by Django 2.1.7 on 2019-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190316_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unityobject',
            name='db_crc32',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
